package oapi

import (
	"bytes"
	"text/template"
)

var tpl = template.Must(template.New("pkg").Parse(
	`// Code generated by oapi-go, DO NOT EDIT.
package {{.PkgName}}

// OpenAPIJsonSpec is json generated specification produced 
// by oapi-go tool.
const OpenAPIJsonSpec = ` + "`" + `{{.OpenAPIJson}}` + "`" + `
`))

type tpldata struct {
	PkgName     string
	OpenAPIJson string
}

func produceGoFile(pkg tpldata) ([]byte, error) {
	bx := bytes.NewBuffer([]byte{})
	err := tpl.Execute(bx, pkg)
	if err != nil {
		return nil, err
	}
	return bx.Bytes(), nil
}
